import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty } from 'class-validator';

export class ConnectTrainerDto {
  @ApiProperty({ description: 'QR token generated by the staff member' })
  @IsString()
  @IsNotEmpty()
  qrToken: string;
}
